name: PublishChapters

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
      - 'source/**'

  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  render:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Render md
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: source/
          output_dir: pdfs/
          images_dir: source/images
          # for example <img src="./images/file-name.png">
          image_import: ./images
          # Default is true, can set to false to only get PDF files
          build_html: true
          theme: staff/style.css
          extend_default_theme: true
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: source
      #     path: pdfs

      - name: Set secret
        env:
          SECRET_AUTH: ${{ secrets.SECRET_AUTH }}
        run: |
          secrets.me < "$SECRET_AUTH" 
        shell: bash

      - name: Publish Telegra.ph
        run: 'staff/js/index'
          

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add pdfs\*.pdf
          if [ -z "$(git status --porcelain)" ]; then
            echo "PUSH=false" >> $GITHUB_ENV
          else
            git commit -m "<auto> publish after $(git log --pretty=format:"%s" -1)" -a
            echo "PUSH=true" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Push changes
        if: env.PUSH == 'true'
        env:
          PUSH: "fake"
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
